---
server:
  port: 8081

spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
app-stacktrace-enable: true

logging:   
  level:
    root: INFO
    org.hibernate.type: OFF
    org.springframework.web: ERROR
    th.go.rd: DEBUG
#  file: /opt/app/logs/${spring.application.name}.log

#Resource Server        
security:
  oauth2:
    resource:
      id: efiling
      jwt:
        key-uri: https://efiling-intra.pccth.com/rd-staff-oauth-service/oauth/token_key


service-config:
  url:
    swagger-host: 

